[tools]
rojo = { source = "Roblox/rojo-rbx-rojo", version = "=7.2.1" }
rotrieve = { source = "roblox/rotriever", version = "=0.5.5" }
selene = { source = "Roblox/Kampfkarren-selene", version = "=0.25.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.15.1" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "5.x.x" }
