std = "roblox+testez"

[config]
empty_if = { comments_count = true }

[rules]
# remove this once the feature request here is implemented: https://github.com/Kampfkarren/selene/issues/181
global_usage = "allow"
# remove when the Luau type narrowing issues (and the workarounds) are resolved
shadowing = "allow"
